/*
 * Copyright (C) 2014-2014 Wiky L(wiiiky@yeah.net)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * this file is generated by gobj(https://github.com/wiiiky/gobj)
 */

#ifndef __WL_BTER_MENU_H__
#define __WL_BTER_MENU_H__

#include <gtk/gtk.h>
#include "wlbter.h"

G_BEGIN_DECLS
/* Macro for casting a pointer to a WlBterMenu or WlBterMenuClass pointer.
 * Macros for testing whether `object' or `klass' are of type WL_TYPE_BTER_MENU.
 */
#define WL_TYPE_BTER_MENU	(wl_bter_menu_get_type())
#define WL_BTER_MENU(obj)	(G_TYPE_CHECK_INSTANCE_CAST ((obj), WL_TYPE_BTER_MENU, WlBterMenu))
#define WL_BTER_MENU_CLASS(klass)	(G_TYPE_CHECK_CLASS_CAST ((klass), WL_TYPE_BTER_MENU, WlBterMenuClass))
#define WL_IS_BTER_MENU(obj)	(G_TYPE_CHECK_INSTANCE_TYPE ((obj), WL_TYPE_BTER_MENU))
#define WL_IS_BTER_MENU_CLASS(klass)	(G_TYPE_CHECK_CLASS_TYPE ((klass), WL_TYPE_BTER_MENU))
#define WL_BTER_MENU_GET_CLASS(obj)	(G_TYPE_INSTANCE_GET_CLASS ((obj), WL_TYPE_BTER_MENU, WlBterMenuClass))
typedef struct _WlBterMenu WlBterMenu;
typedef struct _WlBterMenuClass WlBterMenuClass;


struct _WlBterMenu {
	GtkMenu parent;
	/*Private */
	WlBter *bter;

	GtkWidget *startDl;
	GtkWidget *pauseDl;
	GtkWidget *propertiesDialog;
};

struct _WlBterMenuClass {
	GtkMenuClass parent_klass;
	/*Private */
};

GType wl_bter_menu_get_type(void) G_GNUC_CONST;

/* Public */

WlBterMenu *wl_bter_menu_new(WlBter * bter);

/*
 * @descrition 根据WlBter设置菜单是否可用
 */
void wl_bter_menu_set_sensitive(WlBterMenu * menu, WlBter * bter);

/*
 * @descrition 获取相关的WlBter
 */
WlBter *wl_bter_menu_get_bter(WlBterMenu * menu);
/*
 * @description 添加菜单项
 */
void wl_bter_menu_append_separator(WlBterMenu * menu);
void wl_bter_menu_append(WlBterMenu * menu, GtkWidget * item);

G_END_DECLS
#endif
