/*
 * Copyright (C) 2014-2014 Wiky L(wiiiky@yeah.net)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * this file is generated by gobj(https://github.com/wiiiky/gobj)
 */

#ifndef __WL_BTER_PROPERTIES_H__
#define __WL_BTER_PROPERTIES_H__

#include <gtk/gtk.h>
#include "libtransmission/transmission.h"
#include "libtransmission/variant.h"

G_BEGIN_DECLS
/* Macro for casting a pointer to a WlBterProperties or WlBterPropertiesClass pointer.
 * Macros for testing whether `object' or `klass' are of type WL_TYPE_BTER_PROPERTIES.
 */
#define WL_TYPE_BTER_PROPERTIES	(wl_bter_properties_get_type())
#define WL_BTER_PROPERTIES(obj)	(G_TYPE_CHECK_INSTANCE_CAST ((obj), WL_TYPE_BTER_PROPERTIES, WlBterProperties))
#define WL_BTER_PROPERTIES_CLASS(klass)	(G_TYPE_CHECK_CLASS_CAST ((klass), WL_TYPE_BTER_PROPERTIES, WlBterPropertiesClass))
#define WL_IS_BTER_PROPERTIES(obj)	(G_TYPE_CHECK_INSTANCE_TYPE ((obj), WL_TYPE_BTER_PROPERTIES))
#define WL_IS_BTER_PROPERTIES_CLASS(klass)	(G_TYPE_CHECK_CLASS_TYPE ((klass), WL_TYPE_BTER_PROPERTIES))
#define WL_BTER_PROPERTIES_GET_CLASS(obj)	(G_TYPE_INSTANCE_GET_CLASS ((obj), WL_TYPE_BTER_PROPERTIES, WlBterPropertiesClass))
typedef struct _WlBterProperties WlBterProperties;
typedef struct _WlBterPropertiesClass WlBterPropertiesClass;


struct _WlBterProperties {
	GtkDialog parent;
	/*Private */
	GtkWidget *torrentSize;
	GtkWidget *haveSize;
	GtkWidget *downloadedSize;
	GtkWidget *uploadedSize;
	GtkWidget *stateLabel;
	GtkWidget *downloadSpeed;
	GtkWidget *uploadSpeed;
	GtkWidget *errorLabel;
	GtkWidget *peerView;
	GtkListStore *peerStore;

	GtkWidget *locationLabel;
	GtkWidget *hashLabel;
	GtkWidget *privacyLabel;
	GtkWidget *originLabel;
	GtkWidget *commentView;
	GtkWidget *creatorLabel;

	tr_torrent *torrent;
	guint timeout;
};

struct _WlBterPropertiesClass {
	GtkDialogClass parentClass;
	/*Private */
};

GType wl_bter_properties_get_type(void) G_GNUC_CONST;

/* Public */
GtkWidget *wl_bter_properties_new(void);
GtkWidget *wl_bter_properties_new_with_torrent(tr_torrent * torrent);
void wl_bter_properties_set_torrent(WlBterProperties * dialog,
									tr_torrent * torrent);

void wl_bter_properties_run(WlBterProperties * dialog);


G_END_DECLS
#endif
